defaults:
  active: true
  save_checkpoint_interval: 100

  lr_scheduler: None
  min_lr: 0
  max_lr: 1e-3
  lr_step_size: 2350
  lr_multiplicator: 0.1

  dataset: coco
  dataset_path: /home/s0555912/.datasets/
  epochs: 6
  max_runtime: 0
  augmentation: true
  batch_size: 24

  network: TRANSFORMER_NET
  bottleneck_type: RESIDUAL_BLOCK
  expansion_factor: 6
  intermediate_activation_fn: PReLU
  final_activation_fn: Sigmoid

  loss_network: vgg16
  content_layers: [relu3_3]
  style_layers: [relu1_2, relu2_2, relu3_3, relu4_3]
  content_weight: 1
  style_weight: 1e7
  total_variation_weight: 0
  style_image_size: 512
  content_image_size: 224
  style_image: the_scream.jpg

  attribution:
    name: The Scream
    author: Edvard Munch
    author_url: https://en.wikipedia.org/wiki/Edvard_Munch
    published_url: http://samling.nasjonalmuseet.no/en/object/NG.M.00939
    publisher: Nasjonalmuseet / Høstland, Børre
    publisher_url: http://nasjonalmuseet.no
    terms_of_use_url: https://creativecommons.org/licenses/by-nc/4.0/deed.en

runs:
  - experiment2__net01__s5__m32__residual_block:
      bottleneck_size: 5
      channel_multiplier: 32

  - experiment2__net02__s5__m16__residual_block:
      bottleneck_size: 5
      channel_multiplier: 16

  - experiment2__net03__s5__m8__residual_block:
      bottleneck_size: 5
      channel_multiplier: 8

  - experiment2__net04__s5__m4__residual_block:
      bottleneck_size: 5
      channel_multiplier: 4

  - experiment2__net05__s4__m32__residual_block:
      bottleneck_size: 4
      channel_multiplier: 32

  - experiment2__net06__s4__m16__residual_block:
      bottleneck_size: 4
      channel_multiplier: 16

  - experiment2__net07__s4__m8__residual_block:
      bottleneck_size: 4
      channel_multiplier: 8

  - experiment2__net08__s4__m4__residual_block:
      bottleneck_size: 4
      channel_multiplier: 4

  - experiment2__net09__s3__m32__residual_block:
      bottleneck_size: 3
      channel_multiplier: 32

  - experiment2__net10__s3__m16__residual_block:
      bottleneck_size: 3
      channel_multiplier: 16

  - experiment2__net11__s3__m8__residual_block:
      bottleneck_size: 3
      channel_multiplier: 8

  - experiment2__net12__s3__m4__residual_block:
      bottleneck_size: 3
      channel_multiplier: 4

  - experiment2__net13__s2__m32__residual_block:
      bottleneck_size: 2
      channel_multiplier: 32

  - experiment2__net14__s2__m16__residual_block:
      bottleneck_size: 2
      channel_multiplier: 16

  - experiment2__net15__s2__m8__residual_block:
      bottleneck_size: 2
      channel_multiplier: 8

  - experiment2__net16__s2__m4__residual_block:
      bottleneck_size: 2
      channel_multiplier: 4