defaults:
  active: true
  save_checkpoint_interval: 100

  lr_scheduler: None
  min_lr: 0
  max_lr: 1e-3
  lr_step_size: 2350
  lr_multiplicator: 0.1

  dataset: coco
  dataset_path: /home/s0555912/.datasets/
  epochs: 4
  max_runtime: 0
  augmentation: true
  batch_size: 24

  network: TRANSFORMER_NET
  bottleneck_type: RESIDUAL_BLOCK
  expansion_factor: 6
  intermediate_activation_fn: PReLU
  final_activation_fn: Sigmoid

  loss_network: vgg16
  content_layers: [relu3_3]
  style_layers: [relu1_2, relu2_2, relu3_3, relu4_3]
  content_weight: 1
  style_weight: 1e7
  total_variation_weight: 0
  style_image_size: 512
  content_image_size: 224

  attribution:
    name: The Starry Night
    author: Vincent van Gogh
    author_url: https://en.wikipedia.org/wiki/Vincent_van_Gogh
    published_url: https://www.moma.org/collection/works/79802
    publisher: Musuem of Modern Arts (MoMA)
    publisher_url: https://www.moma.org
    terms_of_use_url: https://www.moma.org/about/about-this-site/#terms-of-use

runs:
  - experiment__net1__s5__m32__residual_block:
      bottleneck_size: 5
      channel_multiplier: 32

  - experiment__net2__s5__m16__residual_block:
      bottleneck_size: 5
      channel_multiplier: 16

  - experiment__net3__s5__m8__residual_block:
      bottleneck_size: 5
      channel_multiplier: 8

  - experiment__net4__s4__m32__residual_block:
      bottleneck_size: 4
      channel_multiplier: 32

  - experiment__net5__s4__m16__residual_block:
      bottleneck_size: 4
      channel_multiplier: 16

  - experiment__net6__s4__m8__residual_block:
      bottleneck_size: 4
      channel_multiplier: 8

  - experiment__net7__s3__m32__residual_block:
      bottleneck_size: 3
      channel_multiplier: 32

  - experiment__net8__s3__m16__residual_block:
      bottleneck_size: 3
      channel_multiplier: 16

  - experiment__net9__s3__m8__residual_block:
      bottleneck_size: 3
      channel_multiplier: 8