defaults:
  active: true
  save_checkpoint_interval: 100

  lr_scheduler: None
  min_lr: 0
  max_lr: 1e-3
  lr_step_size: 2350
  lr_multiplicator: 0.1

  dataset: coco
  dataset_path: /home/s0555912/.datasets/
  epochs: 1
  max_runtime: 0
  augmentation: false
  batch_size: 16

  network: TRANSFORMER_NET
  channel_multiplier: 8
  bottleneck_size: 5
  bottleneck_type: RESIDUAL_BLOCK
  expansion_factor: 6
  intermediate_activation_fn: PReLU
  final_activation_fn: Sigmoid

  loss_network: vgg16
  content_layers: [relu3_3]
  style_layers: [relu1_2, relu2_2, relu3_3, relu4_3]
  content_weight: 1
  style_weight: 2e7
  total_variation_weight: 0
  style_image_size: 512
  content_image_size: 256

runs:
  # Vincent van Gogh
  - the_starry_night:
      style_image: license-checked/the_starry_night.jpg
      attribution:
        name: The Starry Night
        author: Vincent van Gogh
        published_url: https://www.moma.org/collection/works/79802
        terms_of_use_url: https://www.moma.org/about/about-this-site/#terms-of-use
        credits_to: Musuem of Modern Arts (MoMA)
        credits_to_url: https://www.moma.org

  - portrait_of_joseph_roulin:
      style_image: license-checked/portrait_of_joseph_roulin.jpg
      attribution:
        name: Portrait of Joseph Roulin
        author: Vincent van Gogh
        published_url: https://www.moma.org/collection/works/79105
        terms_of_use_url: https://www.moma.org/about/about-this-site/#terms-of-use
        credits_to: Musuem of Modern Arts (MoMA)
        credits_to_url: https://www.moma.org

  - the_olive_trees:
      style_image: license-checked/the_olive_trees.jpg
      attribution:
        name: The Olive Trees
        author: Vincent van Gogh
        published_url: https://www.moma.org/collection/works/80013
        terms_of_use_url: https://www.moma.org/about/about-this-site/#terms-of-use
        credits_to: Musuem of Modern Arts (MoMA)
        credits_to_url: https://www.moma.org

  # Salvador Dalí
  - the_persistence_of_memory:
      style_image: license-checked/the_persistence_of_memory.jpg
      attribution:
        name: The Persistence of Memory
        author: Salvador Dalí
        published_url: https://www.moma.org/collection/works/79018
        terms_of_use_url: https://www.moma.org/about/about-this-site/#terms-of-use
        credits_to: Musuem of Modern Arts (MoMA)
        credits_to_url: https://www.moma.org

  - the_little_theater:
      style_image: license-checked/the_little_theater.jpg
      attribution:
        name: The Little Theater
        author: Salvador Dalí
        published_url: https://www.moma.org/collection/works/80884
        terms_of_use_url: https://www.moma.org/about/about-this-site/#terms-of-use
        credits_to: Musuem of Modern Arts (MoMA)
        credits_to_url: https://www.moma.org

  # Pablo Picasso
  - meditation:
      style_image: license-checked/meditation.jpg
      attribution:
        name: Meditation
        author: Pablo Picasso
        published_url: https://www.moma.org/collection/works/33823
        terms_of_use_url: https://www.moma.org/about/about-this-site/#terms-of-use
        credits_to: Musuem of Modern Arts (MoMA)
        credits_to_url: https://www.moma.org

  - two_acrobats_with_a_dog:
      style_image: license-checked/two_acrobats_with_a_dog.jpg
      attribution:
        name: Two Acrobats with a Dog
        author: Pablo Picasso
        published_url: https://www.moma.org/collection/works/35378
        terms_of_use_url: https://www.moma.org/about/about-this-site/#terms-of-use
        credits_to: Musuem of Modern Arts (MoMA)
        credits_to_url: https://www.moma.org

  - bathers_in_a_forest:
      style_image: license-checked/bathers_in_a_forest.jpg
      attribution:
        name: Bathers in a Forest
        author: Pablo Picasso
        published_url: https://www.moma.org/collection/works/33370
        terms_of_use_url: https://www.moma.org/about/about-this-site/#terms-of-use
        credits_to: Musuem of Modern Arts (MoMA)
        credits_to_url: https://www.moma.org

  - still_life_with_liqueur_bottle:
      style_image: license-checked/still_life_with_liqueur_bottle.jpg
      attribution:
        name: Still Life with Liqueur Bottle
        author: Pablo Picasso
        published_url: https://www.moma.org/collection/works/78986
        terms_of_use_url: https://www.moma.org/about/about-this-site/#terms-of-use
        credits_to: Musuem of Modern Arts (MoMA)
        credits_to_url: https://www.moma.org

  - ma_jolie:
      style_image: license-checked/ma_jolie.jpg
      attribution:
        name: Ma Jolie
        author: Pablo Picasso
        published_url: https://www.moma.org/collection/works/79051
        terms_of_use_url: https://www.moma.org/about/about-this-site/#terms-of-use
        credits_to: Musuem of Modern Arts (MoMA)
        credits_to_url: https://www.moma.org

  # Pexels
  - photo_of_geological_formation:
      style_image: license-checked/photo_of_geological_formation.jpg
      attribution:
        name: Photo of Geological Formation
        author: Vlad Chețan
        published_url: https://www.pexels.com/photo/photo-of-geological-formation-2537641
        terms_of_use_url: https://www.pexels.com/photo-license
        credits_to: Pexels
        credits_to_url: https://www.pexels.com

  - crystal_glass_on_a_colorful_background:
      style_image: license-checked/crystal_glass_on_a_colorful_background.jpg
      style_weight: 1e7
      attribution:
        name: Crystal Glass On A Colorful Background
        author: Steve Johnson
        published_url: https://www.pexels.com/photo/crystal-glass-on-a-colorful-background-2179374
        terms_of_use_url: https://www.pexels.com/photo-license
        credits_to: Pexels
        credits_to_url: https://www.pexels.com

  - multicolored_abstract_artwork:
      style_image: license-checked/multicolored_abstract_artwork.jpg
      attribution:
        name: Multicolored Abstract Artwork
        author: Sharon McCutcheon
        published_url: https://www.pexels.com/photo/abstract-abstract-painting-art-artistic-1149019
        terms_of_use_url: https://www.pexels.com/photo-license
        credits_to: Pexels
        credits_to_url: https://www.pexels.com

  - multicolored_abstract_art:
      style_image: license-checked/multicolored_abstract_art.jpg
      style_weight: 3e6
      attribution:
        name: Multicolored Abstract Art
        author: Amber Lamoreaux
        published_url: https://www.pexels.com/photo/multicolored-abstract-art-2062637
        terms_of_use_url: https://www.pexels.com/photo-license
        credits_to: Pexels
        credits_to_url: https://www.pexels.com

  # Nasjonalmuseet
  - the_scream:
      style_image: license-checked/the_scream.jpg
      attribution:
        name: The Scream
        author: Edvard Munch
        published_url: http://samling.nasjonalmuseet.no/en/object/NG.M.00939
        terms_of_use_url: https://creativecommons.org/licenses/by-nc/4.0/deed.en
        credits_to: Nasjonalmuseet / Høstland, Børre
        credits_to_url: http://nasjonalmuseet.no