defaults:
  lr_scheduler: None
  min_lr: 0
  max_lr: 1e-3
  lr_step_size: 2350
  lr_multiplicator: 0.1
  dataset: coco
  dataset_path: /home/s0555912/.datasets/
  epochs: 3
  augmentation: false
  batch_size: 16
  active: true
  channel_multiplier: 32
  content_image_size: 256
  style_image_size: 512
  content_weight: 1
  style_weight: 1e7
  total_variation_weight: 1e-6
  bottleneck_type: RESIDUAL_BLOCK
  bottleneck_size: 5
  expansion_factor: 6
  max_runtime: 0
  network: STYLIZED_NET
  save_checkpoint_interval: 100
  intermediate_activation_fn: PReLU
  final_activation_fn: Hardtanh
  content_layers: [relu3_3]
  style_layers: [relu1_2, relu2_2, relu3_3, relu4_3]
  loss_network: vgg16

runs:
  - candy_l: # done
      style_image: candy.jpg # https://bytefreaks.net/photography/neural-style-transfer-candy-style-source/amp
      total_variation_weight: 1e-5
      content_weight: 5
      style_weight: 1e7
      style_image_size: 768
      
  - candy_m: #done
      style_image: candy.jpg # https://bytefreaks.net/photography/neural-style-transfer-candy-style-source/amp
      total_variation_weight: 1e-5
      content_weight: 5
      style_weight: 1e7
      style_image_size: 512

  - candy_s: #done
      style_image: candy.jpg # https://bytefreaks.net/photography/neural-style-transfer-candy-style-source/amp
      total_variation_weight: 1e-5
      content_weight: 5
      style_weight: 1e7
      style_image_size: 256

  - starry_night: # done
      style_image: starry_night.jpg # https://en.wikipedia.org/wiki/File:VanGogh-starry_night_ballance1.jpg
      total_variation_weight: 1e-6
      content_weight: 1
      style_weight: 1e7
      style_image_size: 768

  - the_scream: # done
      style_image: the_scream.jpg # https://commons.wikimedia.org/wiki/File:The_Scream.jpg
      total_variation_weight: 1e-8
      content_weight: 1
      style_weight: 1e7
      style_image_size: 768

  - mosaic_of_trees: # done
      style_image: mosaic_of_trees.jpg # https://www.erinhanson.com/p/mosaic_of_trees
      total_variation_weight: 1e-6
      content_weight: 1
      style_weight: 1e7
      style_image_size: 768

  - shipwreck: # done
      style_image: shipwreck.jpg # https://www.artble.com/artists/joseph_mallord_william_turner/paintings/the_shipwreck
      total_variation_weight: 1e-6
      content_weight: 1
      style_weight: 1e7
      style_image_size: 512

  - seated_nude:
      style_image: seated_nude.jpg # https://www.pablopicasso.org/seated-nude.jsp
      total_variation_weight: 0
      content_weight: 1
      style_weight: 4e7
      style_image_size: 512

  - the_old_guitarist:
      style_image: the_old_guitarist.jpg # https://www.pablopicasso.org/old-guitarist.jsp
      total_variation_weight: 1e-8
      content_weight: 1
      style_weight: 4e7
      style_image_size: 512

  - bread_and_fruit_dish_on_a_table: # done
      style_image: bread_and_fruit_dish_on_a_table.jpg # https://www.pablopicasso.org/bread-and-fruit-dish-on-a-table.jsp
      total_variation_weight: 1e-8
      content_weight: 1
      style_weight: 1e7
      style_image_size: 512

  - vincent_van_gogh_self_portrait:
      style_image: vincent_van_gogh_self_portrait.jpg # https://en.wikipedia.org/wiki/Vincent_van_Gogh
      total_variation_weight: 1e-6
      content_weight: 1
      style_weight: 1e7
      style_image_size: 768

  - coquelicots:
      style_image: coquelicots.jpg # https://www.wikidata.org/wiki/Q3231771
      total_variation_weight: 1e-6
      content_weight: 1
      style_weight: 1e7
      style_image_size: 768

  - cafe_terrace_at_night:
      style_image: cafe_terrace_at_night.jpg # https://www.impressionists.org/cafe-terrace-at-night.jsp
      total_variation_weight: 1e-6
      content_weight: 1
      style_weight: 1e7
      style_image_size: 768