defaults:
  active: true
  save_checkpoint_interval: 100

  lr_scheduler: None
  min_lr: 0
  max_lr: 1e-3
  lr_step_size: 2350
  lr_multiplicator: 0.1

  dataset: coco/train2017
  dataset_path: /home/s0555912/.datasets/
  epochs: 4
  max_runtime: 0
  augmentation: true
  batch_size: 24

  network: TRANSFORMER_NET
  channel_multiplier: 8
  bottleneck_size: 5
  bottleneck_type: RESIDUAL_BLOCK
  expansion_factor: 6
  intermediate_activation_fn: PReLU
  final_activation_fn: Sigmoid

  loss_network: vgg19
  content_layers: [relu4_2]
  style_layers: [relu1_1, relu2_1, relu3_1, relu4_1, relu5_1]
  content_weight: 1
  total_variation_weight: 0
  style_image_size: 512
  content_image_size: 224

runs:
  # Vincent van Gogh
  - vgg19_the_starry_night:
      style_image: the_starry_night.jpg
      style_weight: 2e7
      attribution:
        name: The Starry Night
        author: Vincent van Gogh
        author_url: https://en.wikipedia.org/wiki/Vincent_van_Gogh
        published_url: https://www.moma.org/collection/works/79802
        publisher: Musuem of Modern Arts (MoMA)
        publisher_url: https://www.moma.org
        terms_of_use_url: https://www.moma.org/about/about-this-site/#terms-of-use

  - vgg19_portrait_of_joseph_roulin:
      style_image: portrait_of_joseph_roulin.jpg
      style_weight: 1e7
      attribution:
        name: Portrait of Joseph Roulin
        author: Vincent van Gogh
        author_url: https://en.wikipedia.org/wiki/Vincent_van_Gogh
        published_url: https://www.moma.org/collection/works/79105
        terms_of_use_url: https://www.moma.org/about/about-this-site/#terms-of-use
        publisher: Musuem of Modern Arts (MoMA)
        publisher_url: https://www.moma.org

  - vgg19_the_olive_trees:
      style_image: the_olive_trees.jpg
      style_weight: 2e7
      attribution:
        name: The Olive Trees
        author: Vincent van Gogh
        author_url: https://en.wikipedia.org/wiki/Vincent_van_Gogh
        published_url: https://www.moma.org/collection/works/80013
        publisher: Musuem of Modern Arts (MoMA)
        publisher_url: https://www.moma.org
        terms_of_use_url: https://www.moma.org/about/about-this-site/#terms-of-use

  # Salvador Dalí
  - vgg19_the_persistence_of_memory:
      style_image: the_persistence_of_memory.jpg
      style_weight: 1e7
      attribution:
        name: The Persistence of Memory
        author: Salvador Dalí
        author_url: https://en.wikipedia.org/wiki/Salvador_Dal%C3%AD
        published_url: https://www.moma.org/collection/works/79018
        publisher: Musuem of Modern Arts (MoMA)
        publisher_url: https://www.moma.org
        terms_of_use_url: https://www.moma.org/about/about-this-site/#terms-of-use

  - vgg19_the_little_theater:
      style_image: the_little_theater.jpg
      style_weight: 1e7
      attribution:
        name: The Little Theater
        author: Salvador Dalí
        author_url: https://en.wikipedia.org/wiki/Salvador_Dal%C3%AD
        published_url: https://www.moma.org/collection/works/80884
        publisher: Musuem of Modern Arts (MoMA)
        publisher_url: https://www.moma.org
        terms_of_use_url: https://www.moma.org/about/about-this-site/#terms-of-use

  # Nasjonalmuseet
  - vgg19_the_scream:
      style_image: the_scream.jpg
      style_weight: 1e7
      attribution:
        name: The Scream
        author: Edvard Munch
        author_url: https://en.wikipedia.org/wiki/Edvard_Munch
        published_url: http://samling.nasjonalmuseet.no/en/object/NG.M.00939
        publisher: Nasjonalmuseet / Høstland, Børre
        publisher_url: http://nasjonalmuseet.no
        terms_of_use_url: https://creativecommons.org/licenses/by-nc/4.0/deed.en

  # Pablo Picasso
  - vgg19_meditation:
      style_image: meditation.jpg
      style_weight: 1e7
      attribution:
        name: Meditation
        author: Pablo Picasso
        author_url: https://en.wikipedia.org/wiki/Pablo_Picasso
        published_url: https://www.moma.org/collection/works/33823
        publisher: Musuem of Modern Arts (MoMA)
        publisher_url: https://www.moma.org
        terms_of_use_url: https://www.moma.org/about/about-this-site/#terms-of-use

  - vgg19_two_acrobats_with_a_dog:
      style_image: two_acrobats_with_a_dog.jpg
      style_weight: 2e7
      attribution:
        name: Two Acrobats with a Dog
        author: Pablo Picasso
        author_url: https://en.wikipedia.org/wiki/Pablo_Picasso
        published_url: https://www.moma.org/collection/works/35378
        publisher: Musuem of Modern Arts (MoMA)
        publisher_url: https://www.moma.org
        terms_of_use_url: https://www.moma.org/about/about-this-site/#terms-of-use

  - vgg19_bathers_in_a_forest:
      style_image: bathers_in_a_forest.jpg
      style_weight: 1e7
      attribution:
        name: Bathers in a Forest
        author: Pablo Picasso
        author_url: https://en.wikipedia.org/wiki/Pablo_Picasso
        published_url: https://www.moma.org/collection/works/33370
        publisher: Musuem of Modern Arts (MoMA)
        publisher_url: https://www.moma.org
        terms_of_use_url: https://www.moma.org/about/about-this-site/#terms-of-use

  - vgg19_still_life_with_liqueur_bottle:
      style_image: still_life_with_liqueur_bottle.jpg
      style_weight: 1e7
      attribution:
        name: Still Life with Liqueur Bottle
        author: Pablo Picasso
        author_url: https://en.wikipedia.org/wiki/Pablo_Picasso
        published_url: https://www.moma.org/collection/works/78986
        publisher: Musuem of Modern Arts (MoMA)
        publisher_url: https://www.moma.org
        terms_of_use_url: https://www.moma.org/about/about-this-site/#terms-of-use

  - vgg19_ma_jolie:
      style_image: ma_jolie.jpg
      style_weight: 3e7
      attribution:
        name: Ma Jolie
        author: Pablo Picasso
        author_url: https://en.wikipedia.org/wiki/Pablo_Picasso
        published_url: https://www.moma.org/collection/works/79051
        publisher: Musuem of Modern Arts (MoMA)
        publisher_url: https://www.moma.org
        terms_of_use_url: https://www.moma.org/about/about-this-site/#terms-of-use

  # Pexels
  - vgg19_photo_of_geological_formation:
      style_image: photo_of_geological_formation.jpg
      style_weight: 1e7
      attribution:
        name: Photo of Geological Formation
        author: Vlad Chețan
        author_url: http://vladchetan.ro
        published_url: https://www.pexels.com/photo/photo-of-geological-formation-2537641
        publisher: Pexels
        publisher_url: https://www.pexels.com
        terms_of_use_url: https://www.pexels.com/photo-license

  - vgg19_crystal_glass_on_a_colorful_background:
      style_image: crystal_glass_on_a_colorful_background.jpg
      style_weight: 1e7
      attribution:
        name: Crystal Glass On A Colorful Background
        author: Steve Johnson
        author_url: https://www.pexels.com/@steve
        published_url: https://www.pexels.com/photo/crystal-glass-on-a-colorful-background-2179374
        publisher: Pexels
        publisher_url: https://www.pexels.com
        terms_of_use_url: https://www.pexels.com/photo-license

  - vgg19_multicolored_abstract_artwork:
      style_image: multicolored_abstract_artwork.jpg
      style_weight: 1e6
      attribution:
        name: Multicolored Abstract Artwork
        author: Sharon McCutcheon
        author_url: https://unsplash.com/@sharonmccutcheon
        published_url: https://www.pexels.com/photo/abstract-abstract-painting-art-artistic-1149019
        publisher: Pexels
        publisher_url: https://www.pexels.com
        terms_of_use_url: https://www.pexels.com/photo-license

  - vgg19_multicolored_abstract_art:
      style_image: multicolored_abstract_art.jpg
      style_weight: 3e6
      attribution:
        name: Multicolored Abstract Art
        author: Amber Lamoreaux
        author_url: https://www.etsy.com/shop/AmberLamoreauxArt
        published_url: https://www.pexels.com/photo/multicolored-abstract-art-2062637
        publisher: Pexels
        publisher_url: https://www.pexels.com
        terms_of_use_url: https://www.pexels.com/photo-license

  - vgg19_teal_and_black_abstract_painting:
      style_image: teal_and_black_abstract_painting.jpg
      style_weight: 1e7
      attribution:
        name: Teal And Black Abstract Painting
        author: Anni Roenkae
        author_url: https://www.anniroenkae.com
        published_url: https://www.pexels.com/photo/teal-and-black-abstract-painting-2559624
        publisher: Pexels
        publisher_url: https://www.pexels.com
        terms_of_use_url: https://www.pexels.com/photo-license

  - vgg19_abstract_painting:
      style_image: abstract_painting.jpg
      style_weight: 1e7
      attribution:
        name: Abstract Painting
        author: Anni Roenkae
        author_url: https://www.anniroenkae.com
        published_url: https://www.pexels.com/photo/abstract-painting-2156881
        terms_of_use_url: https://www.pexels.com/photo-license
        publisher: Pexels
        publisher_url: https://www.pexels.com

