from enum import Enum


class NetworkArchitecture(Enum):
    TEXTURE_NET = 0
    TRANSFORMER_NET_CONV_TRANSPOSE = 2
    TRANSFORMER_NET_INTERPOLATE = 3
    TRANSFORMER_NET_CONV_TRANSPOSE_LARGE = 4
    TRANSFORMER_NET_INTERPOLATE_LARGE = 5
    STACH_MOBILE_NET = 6
    STACH_MOBILE_FULL_RESIDUAL_NET = 7
    CUSTOM_TRANSFORMER_NET_INTERPOLATE = 8
    STYLIZED_NET = 9
